services:
  pg-database:
    image: postgres:13
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
      - POSTGRES_DB=ny_taxi
    volumes:
      - "C:/Users/N/Desktop/DE_ZoomCamp/Week1/Docker/docker_sql/ny_taxi_postgres_data:/var/lib/postgresql/data:rw"
    ports:
      - "5434:5432"
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
    volumes:
      - "C:/Users/N/Desktop/DE_ZoomCamp/Week1/Docker/docker_sql/data_pgadmin:/var/lib/pgadmin:rw"
    ports:
      - "8080:80"





